# version: '2'
#
# services:
#   db:
#     image: mysql:5.7
#     ports:
#       - "8001:3306"
#     volumes:
#       - ./_db:/var/lib/mysql
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: wordtest
#       MYSQL_USER: root
#       MYSQL_PASSWORD: root
#
#   wordpress:
#     depends_on:
#       - db
#     image: wordpress:latest
#     ports:
#       - "8000:80"
#     volumes:
#       - ./src:/var/www/html/wp-content/
#     restart: always
#     environment:
#       WORDPRESS_DB_HOST: db:3306
#       WORDPRESS_DB_USER: root
#       WORDPRESS_DB_PASSWORD: root


# version: '2'
# services:
#   db:
#     image: mysql:5.7
#     restart: always
#     ports:
#       - 3307:3306
#     volumes:
#       - ./database:/var/lib/mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: letmein
#     networks:
#       - back
#
#   phpmyadmin:
#     depends_on:
#       - db
#     image: phpmyadmin/phpmyadmin
#     ports:
#       - 8001:80
#     environment:
#       PMA_HOST: db
#       MYSQL_ROOT_PASSWORD: letmein
#     networks:
#       - back
#
#   wordpress:
#     depends_on:
#       - db
#     image: wordpress
#     restart: always
#     ports:
#       - 8000:80
#     volumes:
#       - ./wp-content:/var/www/html/wp-content
#     environment:
#       WORDPRESS_DB_HOST: db:3306
#       WORDPRESS_DB_PASSWORD: letmein
#     ports:
#       - 80:80
#       - 443:443
#     networks:
#       - back
#
# networks:
#   back:
# volumes:
#   database:


version: '2'
services:
  wordpress:
    depends_on:
      - db
    image: wordpress
    restart: always
    volumes:
      - ./wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: letmein
    ports:
      - 8000:80
      - 443:443
    networks:
      - back
  db:
    image: mysql:5.7
    restart: always
    volumes:
       - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: letmein
    networks:
      - back
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8001:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: letmein
    networks:
      - back
networks:
  back:
volumes:
  db_data:
